runs:
  using: composite

  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: bun

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash # Composite jobs must specify the shell.
